# Generated by Django 4.2.5 on 2023-11-05 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True, verbose_name='Children Full Name')),
                ('grade', models.CharField(max_length=50, null=True, verbose_name='Children Grade')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=20, null=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Children Profile',
                'verbose_name_plural': 'Children Profile',
                'db_table': 'profiles-children-profile-list',
            },
        ),
        migrations.CreateModel(
            name='ChildrenSchoolRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=10, null=True, verbose_name='School Code')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=20, null=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('children', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_school_relation', to='profiles.childrenprofile')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.school', verbose_name='Select School')),
            ],
            options={
                'verbose_name': 'Children School Relation',
                'verbose_name_plural': 'Children School Relation',
                'db_table': 'profiles-children-school-relation-list',
            },
        ),
    ]
