# Generated by Django 4.2.5 on 2023-10-12 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True, verbose_name='Children Full Name')),
                ('grade', models.CharField(max_length=50, null=True, verbose_name='Children Grade')),
                ('scode', models.CharField(max_length=10, null=True, verbose_name='School Code')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.school', verbose_name='Select School')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Children Profile',
                'verbose_name_plural': 'Children Profile',
                'db_table': 'profiles-children-profile-list',
            },
        ),
    ]
