# Generated by Django 4.2.5 on 2023-10-01 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100, verbose_name='Address 1')),
                ('address_line_2', models.CharField(blank=True, max_length=100, verbose_name='Address 2')),
                ('image', models.ImageField(blank=True, upload_to='userprofile/', verbose_name='Profile Picture')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=20, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profile',
                'db_table': 'profiles-parent-list',
            },
        ),
        migrations.CreateModel(
            name='ChildrenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True, verbose_name='Children Full Name')),
                ('grade', models.CharField(max_length=50, null=True, verbose_name='Children Grade')),
                ('scode', models.CharField(max_length=10, null=True, verbose_name='School Code')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.school', verbose_name='Select School')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Children Profile',
                'verbose_name_plural': 'Children Profile',
                'db_table': 'profiles-children-profile-list',
            },
        ),
    ]
