# Generated by Django 4.2.5 on 2023-10-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50, verbose_name='Parent First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Parent Last Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Contact No')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Account',
                'db_table': 'accounts-list',
            },
        ),
    ]
