# Generated by Django 4.2.5 on 2023-10-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping')], max_length=100, null=True, verbose_name='Address Type'),
        ),
    ]
