# Generated by Django 4.2.5 on 2023-10-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='userprofile/%Y/%m/%d/', verbose_name='Picture'),
        ),
    ]
