# Generated by Django 4.2.5 on 2023-10-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profilepicture_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending'), ('Blocked', 'Blocked')], default='Pending', max_length=10, verbose_name='Status'),
        ),
    ]
