# Generated by Django 4.2.5 on 2023-10-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('School Wear', 'School Wear'), ('Sports Wear', 'Sports Wear'), ('Spirit Wear', 'Spirit Wear')], default='School Wear', max_length=11, verbose_name='Wear Type')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('sname', models.CharField(help_text='Khalsa Community School: KCS', max_length=250, null=True, unique=True, verbose_name='Short Name')),
                ('code', models.CharField(help_text='Ex: KCS-01 / KCS01', max_length=50, null=True, unique=True, verbose_name='Code')),
                ('logo', models.ImageField(blank=True, help_text='Size (in px): 300x300', null=True, upload_to='category/logos/%Y/%m/%d/', verbose_name='Logo')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Title')),
                ('meta_description', models.TextField(blank=True, max_length=160, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'School',
                'db_table': 'category-school-list',
            },
        ),
    ]
